afes-website/cappuccino-app

- src/components/TypesafeRouter.tsx
よくわからないけどanyつかったら治ったのでヨシ！(index signatureだし…)
> #10: typesaferouterの型

- package.json
- src/App.tsx
- src/assets/styles/theme.ts
- src/components/AccountDrawer.tsx
- src/components/BottomNav.tsx
- src/components/TopBar.tsx
- src/libs/auth.ts
- src/libs/isAxiosError.ts
- src/libs/jwt.ts
- src/libs/routes.ts
- src/pages/Login.tsx
- yarn.lock
close #2 
- `401`: 間違ってんぞ
- その他: unexpected もう一度お試しいただくかウェブサイト班までご連絡ください
副作用とかあるし一応書いておきたさはある~~
めんどうなのでやめました
> #2 user auth

- LICENSE
- package.json
close #19
- docs: add LICENSE
- docs: add license to package.json
> #19 add MIT LICENSE

- .github/workflows/loxcan.yml
- .github/workflows/test_pull_request.yml
- src/App.tsx
- src/libs/title.ts
close #33
動いてくれ～～～ :pray:
- ci: add test pull request workflow
- ci: add loxcan workflow
> #33 pr test / loxcan の導入

- README.md
close #36
package.json に記載されたバージョンを dynamic 参照するようにしました
commit message のガバ英語は許してください
> #36 README の lib ver 表示を改善

- src/components/QRScanner.tsx
- src/components/VideoDeviceSelectModal.tsx
- src/libs/videoDeviceId.ts
- src/types/react-qr-reader.d.ts
fix #46
device id を local storage に保管しています
> #46 Web RTC で使用するデバイスを選択できるように

- .github/workflows/deploy_dev.yml
> #14(2) fix yaml syntax

- src/components/BottomNav.tsx
- src/components/TopBar.tsx
fix #52
ログイン直後の TopBar および BottomNav が意図しない挙動をしていたので修正
> #52 history.listen が怪しいので useEffect に置き換え

- src/assets/styles/theme.ts
- src/components/TopBar.tsx
- src/libs/routes.ts
- src/pages/Home.tsx
close #62
ダークテーマの色は Google Pay からもらってきました
`#000` にするかも悩んだけど、どう？
> #62 ダークテーマをより暗く・戻るボタン改善

- src/components/BottomNav.tsx
- src/components/GuestScan.tsx
- src/components/MaterialSvgIcons.tsx
- src/components/ToggleVisibilityListItem.tsx
- src/libs/compare.ts
- src/libs/routes.ts
- src/pages/exh/ScanHistory.tsx
- src/pages/general/EnterScan.tsx
- src/pages/general/GuestInfo.tsx
> #41 来場者・予約情報照会ページ

- .env
- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- package.json
- src/components/AccountDrawer.tsx
- src/pages/Login.tsx
close #77
- master: `v3.0.0-e7439be-24`
- develop: `v3.0.0-dev-e7439be-32`
- local: `v3.0.0-210614.112127.0`
> #77 バージョンとビルド番号をアプリ内に表示

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
GitHub Actions はシングルクオーテーションしか使えないことを忘れがち
> #77 (#79) バージョンとビルド番号をアプリ内に表示 2

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
> #77 (#79, #81) バージョンとビルド番号をアプリ内に表示 3

- package.json
- src/components/AccountIcon.tsx
- src/components/BottomNav.tsx
- src/components/GuestScan.tsx
- src/components/PermissionIcon.tsx
- src/components/StayStatus.tsx
- src/components/StayStatusCard.tsx
- src/libs/routes.ts
- src/pages/Home.tsx
- src/pages/executive/AllExhStatus.tsx
- src/pages/executive/CheckInScan.tsx
- src/pages/executive/CheckOutScan.tsx
- src/pages/executive/GuestInfo.tsx
- src/pages/exhibition/EnterScan.tsx
- src/pages/exhibition/ExitScan.tsx
- src/pages/exhibition/ScanHistory.tsx
- yarn.lock
close #68 #76
afes-website/cappuccino-back#13 待ち
|      | Package             | Before         | After          |
| :--: | :------------------ | :------------- | :------------- | 
|  ⬆️  | @afes-website/docs  | 2.3.0-alpha.7  | 3.0.0-alpha.15 |
> #68,#76 API v3 への移行

- src/components/StayStatusCard.tsx
> #85 StayStatusCard で API 通信が無限ループする

- src/components/GuestScan.tsx
- src/components/ResultPopup.tsx
- src/libs/errorHandler.ts
- src/pages/executive/CheckInScan.tsx
- src/pages/executive/GuestInfo.tsx
- yarn.lock
> #83 複数人予約に対応

- src/components/AccountDrawer.tsx
- src/components/ExhInfoCard.tsx
- src/components/StayStatusCard.tsx
- src/layouts/Main.tsx
- src/libs/auth.ts
- src/pages/Home.tsx
- src/pages/Login.tsx
- src/pages/executive/CheckInScan.tsx
- src/pages/executive/CheckOutScan.tsx
- src/pages/executive/GuestInfo.tsx
- src/pages/exhibition/EnterScan.tsx
- src/pages/exhibition/ExitScan.tsx
> #94 useAuth()

- src/App.tsx
- src/components/AccountDrawer.tsx
- src/components/GuestScan.tsx
- src/components/SideNav.tsx
- src/components/TopBar.tsx
- src/layouts/Main.tsx
- src/layouts/Tablet.tsx
- src/libs/routes.ts
- src/pages/Account.tsx
- src/pages/executive/CheckInScan.tsx
- src/pages/executive/GuestInfo.tsx
close #92
| | |
| -- | -- |
|  ![image](https://user-images.githubusercontent.com/33474143/125780637-82c7f106-f61d-43be-8de6-0aaabcf8da11.png) | ![image](https://user-images.githubusercontent.com/33474143/125780667-404b7245-1a31-4fcd-b62b-f68540059329.png) |
| ![image](https://user-images.githubusercontent.com/33474143/125780692-22d3cc2e-bd33-408c-bf81-96cb9e7922de.png) |
> #92 iPad 用 UI

- src/components/DirectInputModal.tsx
> #96 直接入力モーダルを上付きに

- src/pages/Login.tsx
> #105 ログインボタンの挙動を改善

- src/components/GuestScan.tsx
> #88 QRコードをスキャンしたときにエラー表示が消えるように

- src/App.tsx
- src/components/LayoutWrapper.tsx
- src/layouts/Main.tsx
- src/layouts/Tablet.tsx
- src/libs/themeMode.ts
> #104 meta theme-color を動的に背景色と同期

- src/components/ActivityLogTimeline.tsx
- src/pages/executive/GuestInfo.tsx
> #110 行動履歴タイムライン

- src/components/AccountDrawer.tsx
- src/components/AccountIcon.tsx
- src/components/ExhInfoCard.tsx
- src/components/SideNav.tsx
- src/components/StayStatusCard.tsx
- src/components/TopBar.tsx
- src/libs/useExhibitionImageUrl.tsx
- src/pages/Account.tsx
- src/pages/executive/AllExhStatus.tsx
- src/pages/executive/GuestInfo.tsx
- yarn.lock
close #29
~~afes-website/docs#265 待ち~~
> #29 アイコン画像表示

- package.json
- src/components/AuthContext.tsx
- src/pages/executive/CheckInScan.tsx
- yarn.lock
> #129 /auth/me に変更・/reservations/_id/check の認証外し

- src/components/AuthContext.tsx
close #133
Twitter と同じ仕様と思っていただければ
> #133 allUsers を使用順にソート

- src/components/CongestionHeatMap.tsx
- src/components/SideNav.tsx
- src/components/TopBar.tsx
- src/layouts/Tablet.tsx
- src/libs/congestionColor.ts
- src/libs/paletteColor.ts
- src/libs/routes.ts
- src/libs/wristBandColor.ts
- src/pages/executive/HeatMap.tsx
close #120
アイコンの出し方まだあんまり気に入ってないけど
> #120 混雑状況ヒートマップ

- src/components/AccountDrawer.tsx
- src/components/PermissionList.tsx
- src/components/SideNav.tsx
- src/pages/Account.tsx
> #140 PermissionList の切り出し

- src/components/QRScanner.tsx
> #138 スキャンを高速化

- src/components/AccountIcon.tsx
- src/components/GuestScan.tsx
- src/components/QRScanner.tsx
- src/components/TopBar.tsx
- src/libs/routes.ts
- src/pages/Login.tsx
- src/pages/LoginQR.tsx
- src/pages/LoginWithQR.tsx
- src/pages/executive/CheckInScan.tsx
- src/pages/executive/GuestInfo.tsx
resolve: #127
- 画面までは作ったけどデザインの所が分からないのでそこだけお願いします
> #127 QRコードログイン

- src/components/AccountDrawer.tsx
- src/components/AccountIcon.tsx
- src/components/SideNav.tsx
- src/pages/Account.tsx
close #141
グラデが合うデザインじゃあないんだよな
> #141 アカウント系デザインをいい感じに

- src/components/ErrorAlert.tsx
> #159 ErrorAlert のデザインを修正

- src/pages/executive/CheckInScan.tsx
> #158 active scanner の変更タイミングを直した

- src/pages/executive/CheckInScan.tsx
- src/pages/executive/GuestInfo.tsx
- yarn.lock
> #200 docs のバージョンを v3.3.3 に

- src/hooks/useHandleRsvInput.ts
- src/hooks/useHandleRsvScan.ts
- src/pages/executive/CheckInScan.tsx
> #205 予約IDを直接入力できるようにした

- src/components/CongestionHeatMap.tsx
> #172 ヒートマップ複数教室対応

- src/pages/Home.tsx
- src/pages/executive/GuestInfo.tsx
close #202 
- check を叩いて有効性も確認
- 人数表示・枠表示
- 入場可能時は緑アラート
- 予約をメインに
- 「文化祭入退場処理」のグループにもメニュー追加
- disabled なタブをわかりやすく
> #202 GuestInfo の予約確認機能拡充

- src/pages/executive/CheckInScan.tsx
> #214 入場スキャン保護者対応

- src/pages/executive/RegisterSpare.tsx
> #213 予備リストバンド登録を新形式の予約QRに対応

- src/hooks/useErrorHandler.ts
- src/pages/executive/CheckInScan.tsx
> #224 長過ぎる Guest ID はスキャンを受け付けないように

- src/components/ReloadButton.tsx
- src/components/StayStatusCard.tsx
fix #121
https://web.dev/i18n/ja/cls/
SWR 入れたら関係ないことだけど
ほかにも CLS 起きてる場所があったら教えてください
> #121 CLS 修正

- src/layouts/Tablet.tsx
> #226 直接入力ボタンの位置を修正

- src/components/GuestScan.tsx
- src/components/QRScanner.tsx
- src/components/ResultPopup.tsx
- src/components/StayStatusCard.tsx
- src/hooks/useDots.ts
- src/pages/exhibition/EnterScan.tsx
- src/types/statusColor.ts
resolve: #223
warning カラーも追加してます
備考：warning 時の statusIcon です
> #223 展示内満員時の表示
